<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>Admin</title>
</head>
<body>
Welcome to Home Page
<a href='../allLogins.jsp'>Log Out</a>
<br/>
<br/>
<a href='adminAddEditDelete.jsp'>Add, Edit information and Delete a customer representative or customer</a>
<br/>
<a href='adminSalesReport.jsp'>Obtain a sales report for a particular month</a>
<br/>
<a href='adminReservations.jsp'>Produce a list of reservations by flight number or by customer name</a>
<br/>
<a href='adminRevenueSummary.jsp'>Produce a summary listing of revenue generated by a particular flight, airline, or customer</a>
<br/>
<a href='adminBiggestCustomer.jsp'>Find out which customer generated most total revenue</a>
<br/>
<a href='adminActiveFlights.jsp'>Produce a list of most active flights (most tickets sold)</a>
</body>
</html>